# Generated by Django 5.1.6 on 2026-08-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('is_billable', models.BooleanField(default=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.tenant'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        choices=[('web', 'Web'), ('db', 'Database'), ('svc', 'Service')], default='svc', max_length=16
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('online', 'Online'),
                            ('offline', 'Offline'),
                            ('not_seen', 'Not Seen on Last Scan'),
                            ('decommissioned', 'Decommissioned'),
                        ],
                        default='online',
                        max_length=16,
                    ),
                ),
                (
                    'risk_level',
                    models.CharField(
                        choices=[
                            ('critical', 'Critical'),
                            ('high', 'High'),
                            ('medium', 'Medium'),
                            ('low', 'Low'),
                            ('none', 'None'),
                        ],
                        default='none',
                        max_length=16,
                    ),
                ),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                (
                    'transport_protocol',
                    models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=8),
                ),
                (
                    'scan_source',
                    models.CharField(
                        choices=[('agent', 'Agent'), ('network', 'Network'), ('manual', 'Manual')],
                        default='network',
                        max_length=16,
                    ),
                ),
                ('is_scanned', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('discovered_on', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.device'
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='inventory.tenant'
                    ),
                ),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-discovered_on'], name='inventory_a_tenant__3c5805_idx')],
            },
        ),
    ]
